title: Ali Adnan
author: Ali Adnan
email: ali.adnani@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hello! I'm an undergraduate student at PolyU that's really interested in data! I've done data engineering and analytics in the past and am learning statistical methods and machine learning to transition into data science as well!
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: thelehhman/plainwhite-jekyll
permalink: /:title/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Ali Adnan
  tagline: Software Dev. & Data
  date_format: "%b %-d, %Y"
  email: ali.adnani@hotmail.com
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github:  aliadnani
    linkedIn: in/ali-adnan-b89303160/
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: aliadnaan
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite
baseurl: ''
plugins:
  - jekyll-seo-tag
#  - jekyll-feed